### ISSUE TITLE
Clash between paper and GitHub

### ISSUE THREAD

**Issue by srinathjayaraman** [dll-ncai/AI-ForestWatch#2]
Hello,

I am a masters student at TU Delft, Netherlands. I am replicating this paper as part of my masters thesis. I noticed a difference between what the original paper says vs. what the GitHub README says regarding UNet training and testing. I have highlighted the difference below (emphasis mine).

**Quote from the paper** - A UNet model is trained with an 18-channel input image and the generated digitized forest cover map of _year 2015_ as ground truth. After a model is trained successfully, _inference is performed on_ the clean Landsat-8 district images of _years 2014 to 2020_.

**Quote from the GitHub README** - We used images from _2014, 2016-2020 for training_ and _2015 for inference_.

I spoke to one of the original authors of the paper, Mr. Annus Zulfiqar, and he clarified that the **original paper contains the right information.** 

Images from 2015 were used as ground truth for training and testing (80/20 split). Real world performance of the UNet was then tested on the images from 2014 and 2016-2020. 

I'm opening this issue so the contradiction can be corrected and further confusion will be prevented.

Thank you!

**Comment by mohsin432** [comment]
Dear @srinathjayaraman Thank you for mentioning the error. The information is updated.
